export const SYD_LIBRARY = [
  {
    id: "data-overview",
    hash: "datu-parskats",
    title: "Datu pārskats",
    description: "Apvieno vairākas savstarpēji saistītas vizualizācijas vienā pārskatā.",
    limitation: "Pārskats izceļ biežākās vērtības, tāpēc retākie ieraksti var nebūt uzreiz redzami.",
    note: "Pārskats ar kopīgiem filtriem un savstarpēji saistītām vizualizācijām.",
    interpretation: "Vizualizācijas rāda datu kopas struktūru un biežumu. Atlase vienā diagrammā filtrē visu pārskatu, bet biežums pats par sevi neparāda parādības nozīmīgumu.",
    renderer: "overview",
    fieldTypes: [],
    scores: { categories: 110, time: 92, relationships: 88, records: 75 },
  },
  {
    id: "category-frequency",
    hash: "kategoriju-biezums",
    title: "Kategoriju biežums",
    description: "Parāda, kuras vērtības izvēlētajā kolonnā sastopamas biežāk.",
    limitation: "Biežums neparāda parādības nozīmīgumu.",
    note: "Piemērots vienas kategoriskas kolonnas vērtību biežuma salīdzināšanai.",
    interpretation: "Biežums parāda ierakstu skaitu, nevis parādības nozīmīgumu. Tukšās vērtības tiek parādītas atsevišķi.",
    renderer: "frequency",
    fieldTypes: ["kategorija", "vairākas vērtības", "persona", "teksts"],
    scores: { categories: 100, time: 35, relationships: 45, records: 55 },
  },
  {
    id: "place-frequency",
    hash: "vietu-sadalijums",
    title: "Vietu sadalījums",
    description: "Salīdzina datos minētās vietas bez automātiskas to piesaistes kartei.",
    limitation: "Vienas vietas dažādi nosaukumi netiek automātiski apvienoti.",
    note: "Piemērots vietu biežuma pārskatam, ja koordinātas vēl nav pārbaudītas.",
    interpretation: "Vietas pieminējumu skaits neparāda to ģeogrāfisko nozīmīgumu. Vienas vietas dažādi nosaukumi var būt saskaitīti atsevišķi.",
    renderer: "frequency",
    fieldTypes: ["vieta"],
    scores: { categories: 95, time: 40, relationships: 50, records: 50 },
  },
  {
    id: "time-distribution",
    hash: "laika-sadalijums",
    title: "Laika sadalījums",
    description: "Parāda ierakstu koncentrāciju un pārtraukumus gados vai datumos.",
    limitation: "Sadalījumu var ietekmēt avotu saglabāšanās un atlase.",
    note: "Piemērots, lai pamanītu koncentrāciju un pārtraukumus laikā.",
    interpretation: "Ierakstu skaits konkrētā periodā var atspoguļot gan vēsturisku aktivitāti, gan avotu saglabāšanos un datu vākšanas izvēles.",
    renderer: "time",
    fieldTypes: ["gads", "datums", "skaitlis"],
    scores: { categories: 45, time: 100, relationships: 30, records: 40 },
  },
  {
    id: "category-comparison",
    hash: "pazimju-saistiba",
    title: "Divu kategoriju salīdzinājums",
    description: "Parāda, kuras divu kolonnu vērtību kombinācijas datos atkārtojas.",
    limitation: "Vērtību biežums neapliecina cēloņsakarību.",
    note: "Piemērots divu kategorisku pazīmju savstarpējā sadalījuma izpētei.",
    interpretation: "Vērtību kombināciju biežums neapliecina cēloņsakarību. Retas kombinācijas var būt saistītas arī ar nepilnīgiem datiem.",
    renderer: "comparison",
    fieldTypes: ["kategorija", "vieta", "persona", "vairākas vērtības", "teksts"],
    scores: { categories: 90, time: 45, relationships: 85, records: 45 },
  },
  {
    id: "bipartite-network",
    hash: "saiknu-tikls",
    title: "Divdaļīgs saikņu tīkls",
    description: "Savieno divu kolonnu vērtības, kas parādās vienā datu ierakstā.",
    limitation: "Kopīga parādīšanās vienā rindā vēl nepierāda vēsturisku vai sociālu saikni.",
    note: "Piemērots divu tipu objektu savstarpējo parādīšanos izpētei.",
    interpretation: "Līnija nozīmē tikai abu vērtību parādīšanos vienā tabulas rindā. Tā pati par sevi nepierāda tiešu, vēsturisku vai sociālu saikni.",
    renderer: "network",
    fieldTypes: ["persona", "vieta", "kategorija", "vairākas vērtības", "teksts"],
    scores: { categories: 92, time: 40, relationships: 100, records: 45 },
  },
  {
    id: "record-browser",
    hash: "ieraksti",
    title: "Ierakstu pārlūks",
    description: "Ļauj pārbaudīt avota ierakstus un salīdzināt to vērtības tabulā.",
    limitation: "Šajā prototipā parādīti pirmie 50 ieraksti.",
    note: "Piemērots avota ierakstu pārbaudei pirms analīzes.",
    interpretation: "Tabulas priekšskatījums nemaina avota vērtības. Šajā prototipā tiek parādīti pirmie 50 ieraksti.",
    renderer: "records",
    fieldTypes: [],
    scores: { categories: 50, time: 55, relationships: 55, records: 100 },
  },
];
